version: "3"
services:
  node:
    container_name: node
    build: ./node
    image: arozendal/rozendal-lists
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./app:/home/node/app
    command: "nodemon -L"
  db:
    container_name: mongo
    image: mongo:3.4.10
