version: "3"
services:
  node:
    container_name: node
    build: ./node
    image: arozendal/rozendal-lists
    user: "node"
    working_dir: /home/node/app
    env_file:
      - ./app/.env
    ports:
      - "80:3000"
    links:
      - db
    volumes:
      - ./app:/home/node/app
    command: "nodemon -L"
  db:
    container_name: mongo
    image: mongo:3.4.10
    environment:
      - MONGO_INITDB_DATABASE=rozendal-lists
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
